### ISSUE TITLE
Array is transformed into Object

### ISSUE THREAD

**Issue by IanNS333** [mindhivefi/ts-mock-firebase#49]
As a firestore model, I have a collection for users, these users have a relation with other collection called maps. For this, I need to have a save the ids of the maps in the user, for which I use an array.
I have a function that I am trying to test which gets a user, changes that array, updates the user and all of this works perfectly with Firebase. 

simplified version:

```
const user = await firestore.doc('users/${uid}').get();
user.ownedMaps.push(mapId);
await firestore.doc('users/${userUid}').update(user);
```

But when I try to use the mock version I get the following error:
`failed: TypeError: user.ownedMaps.push is not a function`

because the actual object is
```
"ownedMaps": Object {
    "0": "1",
 }
```
which is essentially an array without the methods. Any idea on how to fix this?

**Comment by mindhivefi** [comment]
I did a new unit test case for this, but I was not able to repeat the issue. Still quite possible that I am missing something here. :)

How did you create the mock data? If you create the ownedMaps -field as an array, it should work just fine and you should be able to use array object methods. But if it is stored as n map like in this example, it should be treated as an object with numbers as keys.
