### ISSUE TITLE
How do I use to test a firebase cloud function?

### ISSUE THREAD

**Issue by stephenwil** [mindhivefi/ts-mock-firebase#89]
Hi,
   Trying to use this to help test a cloud function using Jest. Can you give a primer in setting it up? My attempts are failing to get it correctly running in a unit test, where I'm going to expect a document to be set in the mock firestore.

**Comment by mindhivefi** [comment]
Hi,
I suppose you have already set up the firebase-admin mock like said on docs: 

> Create a file to [SOURCE_ROOT]/__mocks__/firebase.ts, with content:
> ```typescript
> import { mockFirebase } from 'ts-mock-firebase';
> 
> const firebase = mockFirebase();
> 
> export = firebase;
> ```
To work with firebase cloud functions, it is good also to mock firebase-functions -module. Currently, ts-mock-firebase does not have a mock for that. Someday it will, but I can not promise any time table :) You can use the following code as a starter for `firebase-functions` -mock. Just add it into `firebase-functions.ts` under source root's `__mocks__` -folder like you did with the `firebase-admin`.

```typescript
const functions: any = {
  https: {
    onCall: (...args: any[]) => {
      console.log('functions.auth.user.onCreate: ' + JSON.stringify(args));
    },
  },
  auth: {
    user: () => {
      return {
        onCreate: (...args: any[]) => {
          console.log('functions.auth.user.onCreate: ' + JSON.stringify(args));
        },
      };
    },
  },
  config: () => {
    return {};
  },
};

// tslint:disable-next-line
export = functions;
```
To do the actual testing of the cloud function I recommend to use the following pattern: 

```typescript
export const _myCloudFunction = (
  data: RegisterNewMemberData,
  context: CallableContext
) => {
  // my test here
}

export const myCloudFunction = functions.https.onCall(_myCloudFunction);
```
With Jest write your tests against that `_myCloudFunction` -function to by pass functions -related code. I hope this will help. Please let me know how did it go.
